## Usage
This Notebook is made to do analysis based on the data transfered/received from and to the C++ Image Enhancer file.

In [9]:
from PIL import Image
import numpy as np

### Read Image 
Read the image for the pixel values and then writes it into a CSV file.

In [14]:
im = Image.open("static/input_image_1.jpg").convert('L') # 8-bit Mode convert

# pixels = list(im.getdata())

# # print(pixels)
# # width, height = im.size
# # pixels = [pixels[i * width:(i + 1) * width] for i in xrange(height)]

# px = im.load()
# print(px[4,2])

pixel_data = np.asarray(im)
print(pixel_data)
print(pixel_data.shape)
np.savetxt('pixel_data.csv', pixel_data)

[[34 34 34 ... 17 16 16]
 [34 34 34 ... 17 16 16]
 [33 33 33 ... 17 16 16]
 ...
 [35 35 35 ... 14 16 16]
 [35 35 35 ... 14 15 15]
 [35 35 35 ... 15 16 16]]
(1200, 1562)


# Read CSV into Image

The purpose of this function, is to take the pixel data in the form of a CSV and reconstruct it into an image